version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_chatapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp_db
      MYSQL_USER: chatapp_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
